### ISSUE TITLE
MonkeDev - API

### ISSUE THREAD

**Issue by Mafia-7777** [TheApiList/data#2]
Url: https://api.monke.vip/
---
Description: An API developed MonkeDev, That contains image manipulation, animal facts, animal images/gifs, and much more yet to come.
---
Author: MonkeDev
---
GitHub: https://github.com/MonkeDev/API/
---
Version: 1.0.0

**Comment by Maksiooo** [comment]
Very good Api! I will send your API in a moment

**Comment by Maksiooo** [comment]
Your api was added. Have a nice day!
